name: "Publish Docker Image"
description: "Pushes Docker image to a registry using docker/build-push-action. Supports build args from env variable and file, and uses tar for build cache if needed. No multi-arch, no QEMU."

runs:
  using: "composite"
  steps:
    - name: Pre Step (Publish Docker Image)
      shell: bash
      run: |
        echo "[PRE] Placeholder for pre-publish actions."

    - name: Validate Inputs and Environment (Docker Publish)
      uses: ./cicd-shared-lib/.github/actions/utils/validate-inputs
      with:
        actionInputs: |
          GHA_CICD_DOCKERFILE_PATH: "${{ env.GHA_CICD_DOCKERFILE_PATH }}"
          GHA_CICD_DOCKER_CONTEXT: "${{ env.GHA_CICD_DOCKER_CONTEXT }}"
          GHA_CICD_DOCKER_IMAGE_URLS: "${{ env.GHA_CICD_DOCKER_IMAGE_URLS }}"
          GHA_CICD_DOCKER_BUILD_ARGS: "${{ env.GHA_CICD_DOCKER_BUILD_ARGS }}"
          GHA_CICD_DOCKER_BUILD_ARGS_FILE: "${{ env.GHA_CICD_DOCKER_BUILD_ARGS_FILE }}"
          GHA_CICD_DOCKER_CONFIG_JSON: "${{ env.GHA_CICD_DOCKER_CONFIG_JSON != '' }}"
        requiredInputs: |
          - GHA_CICD_DOCKER_CONTEXT
          - GHA_CICD_DOCKERFILE_PATH
          - GHA_CICD_DOCKER_IMAGE_URLS
          - GHA_CICD_DOCKER_CONFIG_JSON
        optionalInputs: |
          - GHA_CICD_DOCKER_BUILD_ARGS
          - GHA_CICD_DOCKER_BUILD_ARGS_FILE
        filesPathInputs: |
          - GHA_CICD_DOCKERFILE_PATH
          - GHA_CICD_DOCKER_BUILD_ARGS_FILE
        typeValidations: |
          string:
            - GHA_CICD_DOCKERFILE_PATH
            - GHA_CICD_DOCKER_CONTEXT
            - GHA_CICD_DOCKER_BUILD_ARGS
            - GHA_CICD_DOCKER_BUILD_ARGS_FILE
            - GHA_CICD_DOCKER_IMAGE_URLS
            - GHA_CICD_DOCKER_CONFIG_JSON
        delimiterValidations: |
            GHA_CICD_DOCKER_IMAGE_URLS: ","
            GHA_CICD_DOCKER_BUILD_ARGS: " "

    - name: Setup .docker/config.json
      shell: bash
      run: |
        echo "::group::Setting up Docker config"
        mkdir -p "$HOME/.docker"
        echo "$GHA_CICD_DOCKER_CONFIG_JSON" > "$HOME/.docker/config.json"
        echo "Wrote Docker config to $HOME/.docker/config.json"
        echo "::endgroup::"

    - name: Prepare Build Args
      id: prep_build_args
      shell: bash
      run: |
        BUILD_ARGS=$(python3 "./cicd-shared-lib/.github/actions/docker-wrapper/utils/prepare_build_args.py")
        echo "build-args<<EOF" >> $GITHUB_OUTPUT
        echo "$BUILD_ARGS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Push Docker Image to Registry
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.GHA_CICD_DOCKER_CONTEXT }}
        file: ${{ env.GHA_CICD_DOCKERFILE_PATH }}
        tags: ${{ env.GHA_CICD_DOCKER_IMAGE_URLS }}
        build-args: ${{ steps.prep_build_args.outputs.build-args }}
        push: true

    - name: Post Step (Publish Docker Image)
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        echo "[POST] Placeholder for post-publish actions."