name: "Publish Multi-Arch Docker Images"
description: "Pushes multi-arch Docker images to registry using Docker buildx. Handles per-platform Dockerfile and build args from both file and env. No per-platform tags, pushes only unified image URLs from GHA_CICD_DOCKER_IMAGE_URLS (comma separated)."

runs:
  using: "composite"
  steps:
    - name: Set up QEMU (for cross-arch builds)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Multi-Arch Images (comma separated image URLs)
      shell: bash
      run: |
        set -e
        IMAGE_URLS="${GHA_CICD_DOCKER_IMAGE_URLS}"
        PLATFORMS="${GHA_CICD_DOCKER_PLATFORMS:-}"
        DOCKER_CONTEXT="${GHA_CICD_DOCKER_CONTEXT:-.}"

        IFS=',' read -ra image_url_list <<< "$IMAGE_URLS"

        if [ -z "$PLATFORMS" ]; then
          # Single arch publish
          for image_url in "${image_url_list[@]}"; do
            DOCKERFILE_PATH="${GHA_CICD_DOCKERFILE_PATH:-Dockerfile}"
            BUILD_ARG_OPTIONS=$(python3 "$GITHUB_ACTION_PATH/prepare_build_args.py" | tail -n 1)

            echo "::group::Publishing $image_url (single arch)"
            docker buildx build \
              -t "$image_url" \
              --file "$DOCKERFILE_PATH" \
              $BUILD_ARG_OPTIONS \
              --push \
              "$DOCKER_CONTEXT"
            echo "::endgroup::"
          done
        else
          # Multi-arch publish
          for image_url in "${image_url_list[@]}"; do
            DOCKERFILE_PATH="${GHA_CICD_DOCKERFILE_PATH:-Dockerfile}"
            BUILD_ARG_OPTIONS=$(python3 "$GITHUB_ACTION_PATH/prepare_build_args.py" | tail -n 1)

            echo "::group::Publishing $image_url for platforms: $PLATFORMS"
            docker buildx build \
              --platform "$PLATFORMS" \
              -t "$image_url" \
              --file "$DOCKERFILE_PATH" \
              $BUILD_ARG_OPTIONS \
              --push \
              "$DOCKER_CONTEXT"
            echo "::endgroup::"
          done
        fi

    - name: Logout from Docker (cleanup)
      shell: bash
      run: |
        docker logout || true