name: "Publish Multi-Arch Docker Images"
description: "Creates and pushes a multi-arch manifest for all platform images under the main image URL(s) passed in GHA_CICD_DOCKER_IMAGE_URLS."

runs:
  using: "composite"
  steps:
    - name: Push platform images
      shell: bash
      run: |
        set -e
        IMAGE_URLS="${GHA_CICD_DOCKER_IMAGE_URLS}"
        PLATFORMS="${GHA_CICD_DOCKER_PLATFORMS}"

        if [ -z "$IMAGE_URLS" ]; then
          echo "No images to push. Set GHA_CICD_DOCKER_IMAGE_URLS."
          exit 1
        fi

        if [ -z "$PLATFORMS" ]; then
          echo "No platforms specified. Cannot create manifest."
          exit 1
        fi

        IFS=',' read -ra platform_list <<< "$PLATFORMS"
        for image_url in $IMAGE_URLS; do
          for raw_platform in "${platform_list[@]}"; do
            platform_key="${raw_platform//\//_}"
            platform_image="${image_url}-${platform_key}"
            echo "::group::Pushing platform image $platform_image"
            docker push "$platform_image"
            echo "::endgroup::"
          done

          # Create manifest list for the main image tag
          manifest_create_args=""
          for raw_platform in "${platform_list[@]}"; do
            platform_key="${raw_platform//\//_}"
            platform_image="${image_url}-${platform_key}"
            manifest_create_args="$manifest_create_args $platform_image"
          done

          echo "::group::Creating manifest $image_url with:"
          echo $manifest_create_args
          docker manifest create "$image_url" $manifest_create_args

          # Annotate each platform image (optional but recommended)
          for raw_platform in "${platform_list[@]}"; do
            platform_key="${raw_platform//\//_}"
            platform_image="${image_url}-${platform_key}"
            arch=$(echo "$raw_platform" | cut -d'/' -f2)
            docker manifest annotate "$image_url" "$platform_image" --arch "$arch"
          done

          docker manifest push "$image_url"
          echo "::endgroup::"
        done

    - name: Logout from Docker (cleanup)
      shell: bash
      run: |
        docker logout || true