name: "Publish Docker Image"
description: "Pushes Docker image to a registry using docker/build-push-action. Supports build args from env variable and file, and uses tar for build cache if needed. No multi-arch, no QEMU."

runs:
  using: "composite"
  steps:

    - name: Setup .docker/config.json
      shell: bash
      run: |
        echo "::group::Setting up Docker config"
        mkdir -p "$HOME/.docker"
        echo "$GHA_CICD_DOCKER_CONFIG_JSON" > "$HOME/.docker/config.json"
        echo "Wrote Docker config to $HOME/.docker/config.json"
        echo "::endgroup::"

    - name: Prepare Build Args List
      id: prep_build_args
      shell: bash
      run: |
        BUILD_ARGS=$(python3 "./cicd-shared-lib/.github/actions/docker-wrapper/utils/prepare_build_args.py")
        BUILD_ARGS_LIST=$(echo "$BUILD_ARGS" | tr ' ' '\n')
        echo "build-args<<EOF" >> $GITHUB_OUTPUT
        echo "$BUILD_ARGS_LIST" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Push Docker Image to Registry
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.GHA_CICD_DOCKER_CONTEXT }}
        file: ${{ env.GHA_CICD_DOCKERFILE_PATH }}
        tags: ${{ env.GHA_CICD_DOCKER_IMAGE_URLS }}
        build-args: ${{ steps.prep_build_args.outputs.build-args }}
        push: true
