name: "Publish Multi-Arch Docker Images"
description: "Pushes multi-arch Docker images to registry using docker/build-push-action. Accepts comma-separated image URLs as tags and platforms. Build args are formed in a separate step and passed as a list."

runs:
  using: "composite"
  steps:
    - name: Set up QEMU (for cross-arch builds)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Prepare build args list
      id: prep_build_args
      shell: bash
      run: |
        python3 "$GITHUB_ACTION_PATH/prepare_build_args.py" > build_args_list.txt
        echo "build_args<<EOF" >> $GITHUB_OUTPUT
        cat build_args_list.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Push Multi-Arch Image(s) to Registry (single step, all tags)
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.GHA_CICD_DOCKER_CONTEXT }}
        file: ${{ env.GHA_CICD_DOCKERFILE_PATH}}
        platforms: ${{ env.GHA_CICD_DOCKER_PLATFORMS}}
        tags: ${{ env.GHA_CICD_DOCKER_IMAGE_URLS }}
        build-args: ${{ steps.prep_build_args.outputs.build_args }}
        push: true
        cache-from: type=local,src=./.buildx-cache
        cache-to: type=local,dest=./.buildx-cache,mode=max

    - name: Logout from Docker (cleanup)
      shell: bash
      run: |
        docker logout || true