name: "Docker Local Build & Tar Export"
description: "Builds Docker image for default runner arch, supports build args from env/file, and exports as tar."

runs:
  using: "composite"
  steps:

    - name: Prepare Build Args
      id: prep_build_args
      shell: bash
      run: |
        BUILD_ARGS=$(python3 "./cicd-shared-lib/.github/actions/docker-wrapper/utils/prepare_build_args.py")
        # Convert space-separated to newline-separated for docker/build-push-action
        BUILD_ARGS_LIST=$(echo "$BUILD_ARGS" | tr ' ' '\n')
        echo "build-args<<EOF" >> $GITHUB_OUTPUT
        echo "$BUILD_ARGS_LIST" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Build Docker Image and Export Tar
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.GHA_CICD_DOCKER_CONTEXT }}
        file: ${{ env.GHA_CICD_DOCKERFILE_PATH }}
        tags: ${{ env.GHA_CICD_LOCAL_IMAGE_NAME }}
        build-args: ${{ steps.prep_build_args.outputs.build-args }}
        call: check
        push: false