name: "Lint (Docker)"
description: "Lint a single Dockerfile using Hadolint. All config via GHA_CICD_ env vars. Groups output and uses GitHub logging functions for better visibility."

runs:
  using: "composite"
  steps:
    - name: Hadolint Linting
      uses: docker://hadolint/hadolint:latest
      with:
        entrypoint: sh
        args:
          - -c
          - |
            echo "::group::Hadolint Linting Start"
            DOCKERFILE="${GHA_CICD_DOCKERFILE_PATH:-Dockerfile}"
            HADOLINT_CONFIG="${GHA_CICD_HADOLINT_CONFIG:-}"
            echo "Linting Dockerfile: $DOCKERFILE"
            if [ -n "$HADOLINT_CONFIG" ]; then
              echo "Hadolint config: $HADOLINT_CONFIG"
            else
              echo "No Hadolint config file provided. Using default rules."
            fi
            echo "::group::Hadolint Version"
            hadolint --version | tee hadolint-report.txt
            echo "::endgroup::"
            echo "::group::Linting Output"
            if [ -n "$HADOLINT_CONFIG" ] && [ -f "$HADOLINT_CONFIG" ]; then
              hadolint --config "$HADOLINT_CONFIG" "$DOCKERFILE" | tee -a hadolint-report.txt
            else
              hadolint "$DOCKERFILE" | tee -a hadolint-report.txt
            fi
            echo "::endgroup::"
            echo "::endgroup::Hadolint Linting End"

    - name: Upload Hadolint Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: hadolint-report
        path: hadolint-report.txt