name: "Dockerfile Lint"
description: |
  Validates Dockerfile syntax using Docker BuildKit.
  Fails if the Dockerfile or build context is invalid.
  You can skip specific lint checks by setting the GHA_CICD_DOCKERFILE_LINT_SKIP_CHECKS environment variable.
runs:
  using: "composite"
  steps:
    - name: Lint Dockerfile (BuildKit Syntax Check)
      shell: bash
      run: |
        echo "::group::Dockerfile Linting"
        echo "==> Starting lint for Dockerfile: $GHA_CICD_DOCKERFILE_PATH"
        docker build --check \
          --file "$GHA_CICD_DOCKERFILE_PATH" \
          --build-arg "BUILDKIT_DOCKERFILE_CHECK=skip=${GHA_CICD_DOCKERFILE_LINT_SKIP_CHECKS}" \
          "$GHA_CICD_DOCKER_CONTEXT" 2>&1 | tee docker_lint_output.txt
        echo "::endgroup::"

    - name: Upload Dockerfile Lint Report Artifact
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: dockerfile-lint-report-${{ github.run_id }}-${{ github.job }}
        path: docker_lint_output.txt
        overwrite: true