name: "Docker Local Build & Tar Export"
description: "Builds Docker image for default runner arch, supports build args from env/file, and exports as tar."

runs:
  using: "composite"
  steps:


    - name: Build Docker Image and Export Tar
      uses: docker/build-push-action@v6
      with:
        context: ${{ env.GHA_CICD_DOCKER_CONTEXT }}
        file: ${{ env.GHA_CICD_DOCKERFILE_PATH }}
        build-args: "BUILDKIT_DOCKERFILE_CHECK=skip=ConsistentInstructionCasing ,StageNameCasing;error=false"
        call: check
