name: "Scan (Xray)"
description: "Performs JFrog Xray vulnerability scan on a built Docker image tarball. Uses only GHA_CICD_ env vars for configuration."

runs:
  using: "composite"
  steps:
    - name: Perform Xray Scan
      shell: bash
      run: |
        if [ "${GHA_CICD_RUN_XRAY_SCAN}" != "true" ]; then
          echo "Xray scan skipped"
          exit 0
        fi

        docker run --rm \
          -v "$GITHUB_WORKSPACE:/workspace" \
          -w /workspace \
          "${GHA_CICD_XRAY_SCAN_IMAGE}" \
          sh -c '
            set -e
            curl -k -fL "${GHA_CICD_JFROG_CLI_URL}" -o /usr/local/bin/jf
            chmod +x /usr/local/bin/jf
            mkdir -p /usr/local/share/ca-certificates
            if [ -n "${GHA_CICD_NBN_CERT_URL}" ]; then
              curl -k "${GHA_CICD_NBN_CERT_URL}" -o /usr/local/share/ca-certificates/nbn.crt
              update-ca-trust extract || update-ca-certificates || true
            fi
            export JFROG_CLI_LOG_LEVEL="${GHA_CICD_XRAY_LOG:-INFO}"
            jf config add apro \
              --url="${GHA_CICD_APRO_BASE_URL}" \
              --artifactory-url="${GHA_CICD_APRO_BASE_URL}" \
              --xray-url="${GHA_CICD_APRO_BASE_URL}/xray" \
              --user="${GHA_CICD_APRO_USERNAME}" \
              --password="${GHA_CICD_APRO_PASSWORD}" \
              --interactive=false
            mkdir -p xrayReport
            REPORT_NAME="xray-${GITHUB_RUN_ID}"
            jf scan "${GHA_CICD_TEMP_IMAGE_TAR}" --watches "${GHA_CICD_WATCHES}" --format=table --fixable-only > xrayReport/$REPORT_NAME.txt
            cat xrayReport/$REPORT_NAME.txt
            ALL_SEVERITIES="${GHA_CICD_ALL_SEVERITIES:-Critical High Medium Low}"
            FOUND_VULN=0
            for SEV in $ALL_SEVERITIES; do
              if ! echo "${GHA_CICD_IGNORED_SEVERITIES}" | grep -qw "$SEV"; then
                if grep -iq "$SEV" xrayReport/$REPORT_NAME.txt; then
                  FOUND_VULN=1
                  echo "Found blocking severity: $SEV"
                fi
              fi
            done
            jf config remove apro --quiet
            if [ $FOUND_VULN -gt 0 ]; then
              echo "Build failed due to Xray vulnerabilities."
              exit 1
            fi
          '

    - name: Upload Xray Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() && env.GHA_CICD_RUN_XRAY_SCAN == 'true' }}
      with:
        name: xray-report-${{ github.run_id }}-${{ github.job }}
        path: xrayReport/xray-${{ github.run_id }}.txt
        overwrite: true