name: "Docker Wrapper"
description: "Reusable Docker CI/CD wrapper for lint, build, test, scan, and publish. All configuration/secrets via environment variables with GHA_CICD_ prefix. Layered properties loading for global, stack, and project overrides."

inputs:
  run_lint:
    description: "Enable lint step (can be overridden by GHA_CICD_RUN_LINT env var)"
    required: false
    default: "false"
  run_build:
    description: "Enable build step (can be overridden by GHA_CICD_RUN_BUILD env var)"
    required: false
    default: "false"
  run_test:
    description: "Enable test step (can be overridden by GHA_CICD_RUN_TEST env var)"
    required: false
    default: "false"
  run_scan:
    description: "Enable scan step (can be overridden by GHA_CICD_RUN_SCAN env var)"
    required: false
    default: "false"
  run_publish:
    description: "Enable publish step (can be overridden by GHA_CICD_RUN_PUBLISH env var)"
    required: false
    default: "false"
  properties_path:
    description: "Path to project-specific properties file"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    # Export shared FG PAT token if set
    - name: Export Shared FG PAT token runner env variable to GitHub Actions env
      shell: bash
      run: |
        if [ -n "$GHA_SHAREDLIB_FG_TOKEN" ]; then
          echo "GHA_SHAREDLIB_FG_TOKEN=$GHA_SHAREDLIB_FG_TOKEN" >> $GITHUB_ENV
        fi

    # Checkout CICD Shared Repository for utilities and stack properties
    - name: Checkout CICD Shared Repository - DW
      id: dw_checkout_shared_lib
      if: env.CICD_SHARED_LIB_EXISTS != 'true'
      uses: actions/checkout@v4
      with:
        repository: "${{ env.action_repository }}"
        ref: "${{ env.action_ref }}"
        #token: "${{ env.GHA_SHAREDLIB_FG_TOKEN }}"
        path: 'cicd-shared-lib'
      env:
        action_ref: "${{ github.action_ref }}"
        action_repository: "${{ github.action_repository }}"

    # Set CICD_SHARED_LIB_EXISTS variable if checkout was successful
    - name: Set CICD_SHARED_LIB_EXISTS variable if checkout was successful
      if: steps.dw_checkout_shared_lib.outcome == 'success'
      shell: bash
      run: echo "CICD_SHARED_LIB_EXISTS=true" >> $GITHUB_ENV

    # Import global properties
    - name: Import Common Properties
      uses: ./cicd-shared-lib/.github/actions/utils/import-properties
      with:
        files: ./cicd-shared-lib/.github/actions/utils/properties/common.properties

    # Import Docker stack-specific properties
    - name: Import Docker Properties
      uses: ./cicd-shared-lib/.github/actions/utils/import-properties
      with:
        files: ./cicd-shared-lib/.github/actions/docker-wrapper/properties/docker.properties

    # Import project-specific properties (if provided)
    - name: Import Project Properties (if provided)
      if: ${{ inputs.properties_path != '' }}
      uses: ./cicd-shared-lib/.github/actions/utils/import-properties
      with:
        files: ${{ inputs.properties_path }}

    # Validate all env variables and key inputs (only using validate-inputs utility)
    - name: Validate Inputs and Environment
      uses: ./cicd-shared-lib/.github/actions/utils/validate-inputs
      with:
        actionInputs: |
          GHA_CICD_RUN_LINT: "${{ env.GHA_CICD_RUN_LINT || inputs.run_lint }}"
          GHA_CICD_RUN_BUILD: "${{ env.GHA_CICD_RUN_BUILD || inputs.run_build }}"
          GHA_CICD_RUN_TEST: "${{ env.GHA_CICD_RUN_TEST || inputs.run_test }}"
          GHA_CICD_RUN_SCAN: "${{ env.GHA_CICD_RUN_SCAN || inputs.run_scan }}"
          GHA_CICD_RUN_PUBLISH: "${{ env.GHA_CICD_RUN_PUBLISH || inputs.run_publish }}"
          # Example docker env vars (these must be set by the workflow, not as action inputs)
          GHA_CICD_DOCKER_IMAGE: "${{ env.GHA_CICD_DOCKER_IMAGE }}"
          GHA_CICD_DOCKER_REGISTRY: "${{ env.GHA_CICD_DOCKER_REGISTRY }}"
          GHA_CICD_DOCKERFILE_PATH: "${{ env.GHA_CICD_DOCKERFILE_PATH }}"
          GHA_CICD_DOCKER_CONTEXT: "${{ env.GHA_CICD_DOCKER_CONTEXT }}"
          GHA_CICD_DOCKER_BUILD_ARGS: "${{ env.GHA_CICD_DOCKER_BUILD_ARGS }}"
          GHA_CICD_DOCKER_PUSH_URLS: "${{ env.GHA_CICD_DOCKER_PUSH_URLS }}"
          GHA_CICD_DOCKER_SCAN_CONFIG: "${{ env.GHA_CICD_DOCKER_SCAN_CONFIG }}"
        requiredInputs: |
          - GHA_CICD_DOCKER_IMAGE
          - GHA_CICD_DOCKER_REGISTRY
          - GHA_CICD_DOCKERFILE_PATH
          - GHA_CICD_DOCKER_CONTEXT
        optionalInputs: |
          - GHA_CICD_RUN_LINT
          - GHA_CICD_RUN_BUILD
          - GHA_CICD_RUN_TEST
          - GHA_CICD_RUN_SCAN
          - GHA_CICD_RUN_PUBLISH
          - GHA_CICD_DOCKER_BUILD_ARGS
          - GHA_CICD_DOCKER_PUSH_URLS
          - GHA_CICD_DOCKER_SCAN_CONFIG
        filesPathInputs: |
          - GHA_CICD_DOCKERFILE_PATH
        typeValidations: |
          booleanString:
            - GHA_CICD_RUN_LINT
            - GHA_CICD_RUN_BUILD
            - GHA_CICD_RUN_TEST
            - GHA_CICD_RUN_SCAN
            - GHA_CICD_RUN_PUBLISH
          string:
            - GHA_CICD_DOCKER_IMAGE
            - GHA_CICD_DOCKER_REGISTRY
            - GHA_CICD_DOCKERFILE_PATH
            - GHA_CICD_DOCKER_CONTEXT
            - GHA_CICD_DOCKER_BUILD_ARGS
            - GHA_CICD_DOCKER_PUSH_URLS
            - GHA_CICD_DOCKER_SCAN_CONFIG

    # Lint step (uses atomic docker lint action, reads config from env)
    - name: Lint (Docker)
      if: ${{ env.GHA_CICD_RUN_LINT == 'true' || inputs.run_lint == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/lint

    # Build step (uses atomic docker build action)
    - name: Build (Docker)
      if: ${{ env.GHA_CICD_RUN_BUILD == 'true' || inputs.run_build == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/build

    # Test step (uses atomic docker test action)
    - name: Test (Docker)
      if: ${{ env.GHA_CICD_RUN_TEST == 'true' || inputs.run_test == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/test

    # Scan step (uses atomic docker scan action)
    - name: Scan (Docker)
      if: ${{ env.GHA_CICD_RUN_SCAN == 'true' || inputs.run_scan == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/scan

    # Publish step (uses atomic docker publish action)
    - name: Publish (Docker)
      if: ${{ env.GHA_CICD_RUN_PUBLISH == 'true' || inputs.run_publish == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/publish