name: "Docker Wrapper"
description: "Reusable Docker CI/CD wrapper for lint, build, test, scan, and publish. All configuration/secrets via environment variables with GHA_CICD_ prefix. Layered properties loading for global, stack, and project overrides."

inputs:
  run_lint:
    description: "Enable lint step"
    required: false
    default: "false"
  run_build:
    description: "Enable build step"
    required: false
    default: "false"
  run_test:
    description: "Enable test step"
    required: false
    default: "false"
  run_scan:
    description: "Enable scan step"
    required: false
    default: "false"
  run_publish:
    description: "Enable publish step"
    required: false
    default: "false"
  properties_path:
    description: "Path to project-specific properties file"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Export Shared FG PAT token runner env variable to GitHub Actions env
      shell: bash
      run: |
        if [ -n "$GHA_SHAREDLIB_FG_TOKEN" ]; then
          echo "GHA_SHAREDLIB_FG_TOKEN=$GHA_SHAREDLIB_FG_TOKEN" >> $GITHUB_ENV
        fi

    - name: Checkout CICD Shared Repository - DW
      id: dw_checkout_shared_lib
      if: env.CICD_SHARED_LIB_EXISTS != 'true'
      uses: actions/checkout@v4
      with:
        repository: "${{ env.action_repository }}"
        ref: "${{ env.action_ref }}"
        #token: "${{ env.GHA_SHAREDLIB_FG_TOKEN }}"
        path: 'cicd-shared-lib'
      env:
        action_ref: "${{ github.action_ref }}"
        action_repository: "${{ github.action_repository }}"

    - name: Set CICD_SHARED_LIB_EXISTS variable if checkout was successful
      if: steps.dw_checkout_shared_lib.outcome == 'success'
      shell: bash
      run: echo "CICD_SHARED_LIB_EXISTS=true" >> $GITHUB_ENV

    - name: Import Common Properties
      uses: ./cicd-shared-lib/.github/actions/utils/import-properties
      with:
        files: ./cicd-shared-lib/.github/actions/utils/properties/common.properties

    - name: Import Docker Properties
      uses: ./cicd-shared-lib/.github/actions/utils/import-properties
      with:
        files: ./cicd-shared-lib/.github/actions/docker-wrapper/properties/docker.properties

    - name: Import Project Properties (if provided)
      if: ${{ inputs.properties_path != '' }}
      uses: ./cicd-shared-lib/.github/actions/utils/import-properties
      with:
        files: ${{ inputs.properties_path }}

    - name: Validate Inputs and Environment
      uses: ./cicd-shared-lib/.github/actions/utils/validate-inputs
      with:
        actionInputs: |
          run_lint: "${{ inputs.run_lint }}"
          run_build: "${{ inputs.run_build }}"
          run_test: "${{ inputs.run_test }}"
          run_scan: "${{ inputs.run_scan }}"
          run_publish: "${{ inputs.run_publish }}"
          GHA_CICD_DOCKERFILE_PATH: "${{ env.GHA_CICD_DOCKERFILE_PATH }}"
          GHA_CICD_DOCKER_CONTEXT: "${{ env.GHA_CICD_DOCKER_CONTEXT }}"
          GHA_CICD_DOCKER_BUILD_ARGS: "${{ env.GHA_CICD_DOCKER_BUILD_ARGS }}"
          GHA_CICD_DOCKER_PUSH_URLS: "${{ env.GHA_CICD_DOCKER_PUSH_URLS }}"
          GHA_CICD_DOCKER_CONFIG_JSON: |-
                   ${{ env.GHA_CICD_DOCKER_CONFIG_JSON }}
        requiredInputs: |
          - run_lint
          - run_build
          - run_test
          - run_scan
          - run_publish
          - GHA_CICD_DOCKERFILE_PATH
          - GHA_CICD_DOCKER_CONTEXT
        optionalInputs: |
          - GHA_CICD_DOCKER_BUILD_ARGS
          - GHA_CICD_DOCKER_PUSH_URLS
          - GHA_CICD_DOCKER_CONFIG_JSON
        filesPathInputs: |
          - GHA_CICD_DOCKERFILE_PATH
        typeValidations: |
          booleanString:
            - run_lint
            - run_build
            - run_test
            - run_scan
            - run_publish
          string:
            - GHA_CICD_DOCKERFILE_PATH
            - GHA_CICD_DOCKER_CONTEXT
            - GHA_CICD_DOCKER_BUILD_ARGS
            - GHA_CICD_DOCKER_PUSH_URLS
            - GHA_CICD_DOCKER_CONFIG_JSON
        dependencyValidations: |
          run_publish:
            expectedValue: "true"
            dependentInputs:
              - GHA_CICD_DOCKER_PUSH_URLS
              - GHA_CICD_DOCKER_CONFIG_JSON



    - name: Lint (Docker)
      if: ${{ inputs.run_lint == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/lint

    - name: Setup .docker/config.json
      shell: bash
      run: |
        echo "::group::Setting up Docker config"
        mkdir -p "$HOME/.docker"
        echo "$GHA_CICD_DOCKER_CONFIG_JSON" > "$HOME/.docker/config.json"
        echo "Wrote Docker config to $HOME/.docker/config.json"
        echo "::endgroup::"

    - name: Build (Docker)
      if: ${{ inputs.run_build == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/build

    - name: Test (Docker)
      if: ${{ inputs.run_test == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/test

    - name: Scan (Docker)
      if: ${{ inputs.run_scan == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/scan

    - name: Publish (Docker)
      if: ${{ inputs.run_publish == 'true' }}
      uses: ./cicd-shared-lib/.github/actions/docker-wrapper/publish