name: "Maven Wrapper"
description: "Reusable Maven CI/CD wrapper"
inputs:
  run_lint:
    description: "Enable lint step"
    required: false
    default: "false"
  run_build:
    description: "Enable build step"
    required: false
    default: "false"
  run_test:
    description: "Enable test step"
    required: false
    default: "false"
  run_publish:
    description: "Enable publish step"
    required: false
    default: "false"
  properties_path:
    description: "Path to project-specific properties file"
    required: false
runs:
  env:
    b: 200
  using: "composite"
  steps:
    - name: Import Common Properties
      env:
        action: "${{ github.action }}"
        action_path: "${{ github.action_path }}"
        action_ref: "${{ github.action_ref }}"
        action_repository: "${{ github.action_repository }}"
        action_status: "${{ github.action_status }}"
      shell: bash
      run: ls -ltr && env



